config/routes.rb
Rails.application.routes.draw do
  root 'sushi_rolls#index'
  devise_for :users
  resources :sushi_rolls
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sushi_roll.rb
class SushiRoll < ApplicationRecord
  belongs_to :user

  validates_presence_of :name, :price

  # Instance Methods
  def is_too_expensive?
    price > 20 ? true : false
  end

  # Class Methods
  def self.only_spicy
    where("spicy = true")
  end

  def self.only_mild
    where("spicy = false")
  end

  def self.by_price
    order(:price)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :sushi_rolls, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/sushi_rolls_controller.rb
class SushiRollsController < ApplicationController
 before_action :set_roll, except: [:index, :new, :create]

  def index
    @rolls = current_user.sushi_rolls
  end

  def new
    @roll = current_user.sushi_rolls.new
    render partial: "form"
  end

  def create
    @roll = current_user.sushi_rolls.new(sushi_roll_params)  
    if @roll.save
      redirect_to sushi_rolls_url, notice: 'Sushi created!'
    else
      render partial: "form"
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @roll.update(sushi_roll_params)
      redirect_to sushi_rolls_url, notice: 'Sushi Roll was successfully updated.'
    else
      render partial: "form"
    end
  end

  def destroy
    @roll.destroy
    redirect_to sushi_rolls_url, notice: 'Sushi roll destroyed.'
  end

  private
    def set_roll
      @roll = current_user.sushi_rolls.find(params[:id])
    end

    def sushi_roll_params
      params.require(:sushi_roll).permit(:name, :price, :spicy)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sushi_rolls_helper.rb
module SushiRollsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SushiTesting</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sushi_rolls/_form.html.erb
<h1><%= @roll.id ? "Edit Roll" : "Create Roll" %></h1>

<%= form_for @roll do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true, placeholder: "Roll Name"%>

  <%= f.label :price %>
  <%= f.number_field :price, required: true, placeholder: "0"%>
  <p>Because we are a fancy restaurant, we do not allow decimal pricing</p>

  <%= f.label :spicy %>
  <%= f.check_box :spicy %>

  <%= f.submit %>
<% end %>

app/views/sushi_rolls/index.html.erb
<h1>Welcome To Rolls In The Hay Barnyard Sushi</h1>
<h2>Your Current Rolls</h2>
<table>
  <thead>
    <tr><th>Roll</th><th>Price</th><th>Edit</th><th>Delete</th>
  </thead>
  <tbody>
    <% total = 0 %>
    <% @rolls.each do |roll| %>
      <tr>
        <td><%= roll.name %></td>
        <td>$<%= roll.price %></td>
        <td><%= roll.spicy ? "Spicy!" : "" %></td>
        <td><%= link_to "Edit", edit_sushi_roll_path(roll) %></td>
        <td><%= link_to "Delete", roll, method: :delete %>
      </tr>
      <% total += roll.price %>
    <% end %>
  </tbody>
  <tfoot>
    <tr><td colspan=5><strong>Your Total: $<%= total %></strong></td></tr>
  </tfoot>
</table>
<%= link_to "Add New Roll", new_sushi_roll_path %>

app/views/sushi_rolls/new.html.erb
<h1>SushiRolls#new</h1>
<p>Find me in app/views/sushi_rolls/new.html.erb</p>